### ISSUE TITLE
installing fastkaggle on kaggle gives a fastcore version mismatch error

### ISSUE THREAD

**Issue by msapaydin** [fastai/fastkaggle#18]
https://www.kaggle.com/code/jhoward/first-steps-road-to-the-top-part-1 

In this notebook (which I am using to teach a class on ann's at Izmir Institute of Technology for a second time!), pip install fastkaggle command gives the following error:

fastai 2.6.3 requires fastcore<1.5,>=1.3.27, but you have fastcore 1.5.29 which is incompatible.

I tried to install earlier versions of fastkaggle such as 2 or 2.1 but then I got other errors in the above notebook.

**Comment by d3netxer** [comment]
I am experiencing the same problem:

```
# install fastkaggle if not available
try: import fastkaggle
except ModuleNotFoundError:
    !pip install -q fastkaggle

from fastkaggle import *
```

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
fastai 2.6.3 requires fastcore<1.5,>=1.3.27, but you have fastcore 1.5.55 which is incompatible.
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: [https://pip.pypa.io/warnings/venv](https://pip.pypa.io/warnings/venv%3C/span%3E%3Cspan)[ class="ansi-yellow-fg">](https://pip.pypa.io/warnings/venv%3C/span%3E%3Cspan)

**Comment by d3netxer** [comment]
I added this cell before and it resolved my issue.

```
!pip install fastcore==1.4.5 
```
