### ISSUE TITLE
setup_comp() to install packages on non-kaggle platforms 

### ISSUE THREAD

**Issue by bencoman** [fastai/fastkaggle#4]
I've got a PR to go with this, so I thought it useful to move discussion here from the forum.  The issue I had [using fastkaggle on Paperspace](https://forums.fast.ai/t/walkthru-9/96847/21?u=bencoman) turned out to be user error by "not having the latest FastAI installed".  This follows up the subsequent Q&A:      

"Why are the pre-requisite installs only done for Kaggle?"
"Because on Kaggle you always have to install because there’s no persistent environment. Elsewhere you don’t need to update from pip every time you run a notebook."

I see that makes sense for someone using **setup_comp()** frequently on kaggle, 
but it doesn't help a newbie trying **setup_comp()** for the first time on a different platform.  While Paperspace can be configured with a persistent environment, that is dependent on pre-run.sh configuration, and over time package dependencies evolve, so even a persistant environment will get out of date.   Fastkaggle may work one month, and then mysteriously not work next month, or redoing a historical submission.    

Thus I propose the **"install"** spec be applied for all platforms.

The only downside I could think of was that uneccessarily invoking "pip install" slows down non-kaggle platforms, so I've played with some code to streamline that. (and also learn a bit about the fastai code contribution process. I've read [CONTRIBUTING](https://github.com/fastai/fastai/blob/master/CONTRIBUTING.md) and its links.)

Here is the [PR notebook review link](https://app.reviewnb.com/fastai/fastkaggle/pull/5)

**Comment by jph00** [comment]
This isn't something I want to add to this function. It's not what it's for. There is certainly benefit to making it easier to do an initial setup on platforms like paperspace, but I don't want to overload this function to do that too.

Having said that, you are more than welcome to fork this and update it to work how you want!
