### ISSUE TITLE
fastkaggle documentation url not working

### ISSUE THREAD

**Issue by Kelvinthedrugger** [fastai/fastkaggle#7]
Hi there, 

As the title suggested, the fastkaggle documentation url directs me to a 404 not found page, I wonder if there's something unwanted happened. Thanks!

url: https://fastai.github.io/fastkaggle/ , as suggested in the description section of this repo

**Comment by jph00** [comment]
Thanks for letting us know. Fixed now

**Comment by Kelvinthedrugger** [comment]
As someone who watched all the videos about fastai courses from 2019 to 2022, I’m more than happy to contribute to the community, even if it’s just a tiny bug.

I know you’ve probably here this a lot, but thank you again for your great contribution to make deep learning uncool !
